# Site
name: "Astrologia Social"
title: "Astrologia Social"
description: "<b>Nos movemos juntxs</b> en un universo de posibilidades"
# description: "En esta página compartimos información de valor acerca de la astrología moderna y humanista, psicológica, se acompañan procesos de autoconocimiento a través de: cartas natales, revoluciones solares, sinastrias, transitos y otras técnicas como el tarot"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.svg'
baseurl: ''
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'ASWeb'
mailchimp-list: 'https://social.us21.list-manage.com/subscribe/post?u=1d2e3940a00a612226addd315&amp;id=0914bd1a45&amp;f_id=007ceae6f0'
include: ["_pages"]
# permalink: /blog/:categories/:year/:month/:day/:title:output_ext
permalink: /blog/:title
email: info@astrologia.social

social-fb: 'https://www.facebook.com/astrologia.social.latam'
social-ig: 'https://instagram.com/astrologia.social'
social-ts: 'https://www.threads.net/@astrologia.social'
social-wa: 'https://wa.me/5492921435720'
 # more like this
# Authors
authors:
  Franco:
    codename: fran
    name: Franco
    display_name: Fran
    avatar: 'assets/images/miembros/franco.jpg'
    email: info@tecno.social
    description: "Intelectual con enfoque en la crítica social y la intersección entre tecnología y sociedad. Fundador y miembro de TecnoSocial Cooperative desde 2021."
    bio: ""
  Lina:
    codename: lina
    name: Lina
    display_name: 'Lina Marco'
    avatar: 'assets/images/miembros/lina.jpg'
    email: lina@astrologiasocial.org
    web: https://www.astrologia.social/miembros/lina
    description: "Investiga y explora la astrología como puente entre el autoconocimiento, los saberes ancestrales y la experiencia humana."
    bio: "Nacida en Colombia, con Sol y Luna en Géminis y Ascendente en Escorpio, tiene formación en comunicación, publicidad y marketing. Su vínculo con la astrología comenzó como un camino de autoconocimiento y sanación, cuando ningún enfoque tradicional lograba dar sentido a su experiencia interna. En 2020, estudió en la escuela de astrología La Maletra (Bogotá, Colombia), donde, a través de la escritura íntima, profundizó en el misterio astrológico y se unió a diversos grupos de estudio.

Desde entonces, ha explorado la astrología con curiosidad e investigación constante. En 2023, se especializó en Astrología Mundana con Lu Gaitán en Aprende Astrología, y en 2024 inició su certificación como astróloga profesional internacional en el Instituto Superior de Astrología (ISAA) de Argentina.

Acompaña procesos de autoconocimiento y empoderamiento personal a través de la interpretación de mapas astrales con un enfoque humanista y psicológico, integrando técnicas predictivas tradicionales desde una perspectiva no determinista.

Es cofundadora de Astrología Social, un espacio de diálogo y experimentación que reúne proyectos dedicados al estudio del cosmos y su relación con la experiencia humana, ampliando la astrología occidental e integrándola con otros saberes."
  Flor:
    codename: flor
    name: Flor
    display_name: 'Flor Mazziotti'
    avatar: 'assets/images/miembros/flor.jpg'
    email: flor@astrologiasocial.org
    web: https://floralquimicaastrofilosofica.blogspot.com/
    description: "Investiga la astrología desde una mirada filosófica para reconectar con la trascendencia del ser."
    bio: "Flor Mazziotti, creadora de AstroFilosófica, desde 2019 está dedicada a la investigación, práctica y difusión de la astrología, entre otras cosas como; el Tarot y la medicina natural, partiendo de un enfoque filosófico, que permite ahondar en los fundamentos elementales y esenciales de la existencia humana, profundizando en los principios que operan detrás de la Matriz de la realidad para entender el mundo, tanto interno como externo. 

El propósito y la misión, están orientados en colaborar con la re-conexión del sentido de trascendencia superando los condicionamientos, partiendo de la importancia en reconocer el origen divino del ser humano mediante el reconocimiento de lo inmanente, es decir, la cualidad divina que permanece intrínseco en cada ente natural existente."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 3
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
