# Site
name: "Astrologia Social"
title: Astrologia Social"
description: "<b>Nos movemos juntxs</b> en un universo de posibilidades"
# description: "En esta página compartimos información de valor acerca de la astrología moderna y humanista, psicológica, se acompañan procesos de autoconocimiento a través de: cartas natales, revoluciones solares, sinastrias, transitos y otras técnicas como el tarot"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.svg'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'ASWeb'
mailchimp-list: ''
include: ["_pages"]
# permalink: /blog/:categories/:year/:month/:day/:title:output_ext
permalink: /blog/:title
email: lina@astrologia.social

# Authors
authors:
  Franco:
    name: Franco
    display_name: Fran
    avatar: 'assets/images/avatar-sal.png'
    email: info@tecno.social
    description: "Intelectual que es dado a la gula, a los placeres, a la crítica social y a la vida moralmente desordenada"
  Lina:
    display_name: Lina
    avatar: 'assets/images/avatar3.png'
    name: Lina Marco
    email: lina@astrologia.social
    web: lina.astrologia.social
    description: "Astrología para la claridad no para la perfección"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 3
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
