# Site
name: "Astrologia Social"
title: Astrologia Social"
description: "<b>Nos movemos juntxs</b> en un universo de posibilidades"
# description: "En esta página compartimos información de valor acerca de la astrología moderna y humanista, psicológica, se acompañan procesos de autoconocimiento a través de: cartas natales, revoluciones solares, sinastrias, transitos y otras técnicas como el tarot"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.svg'
baseurl: ''
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'ASWeb'
mailchimp-list: 'https://social.us21.list-manage.com/subscribe/post?u=1d2e3940a00a612226addd315&amp;id=0914bd1a45&amp;f_id=007ceae6f0'
include: ["_pages"]
# permalink: /blog/:categories/:year/:month/:day/:title:output_ext
permalink: /blog/:title
email: info@astrologia.social

social-fb: 'https://www.facebook.com/astrologia.social.latam'
social-ig: 'https://instagram.com/astrologia.social'
social-ts: 'https://www.threads.net/@astrologia.social'
social-wa: 'https://wa.me/5492921435720'
 # more like this
# Authors
authors:
  Franco:
    codename: fran
    name: Franco
    display_name: Fran
    avatar: 'assets/images/miembros/franco.jpg'
    email: info@tecno.social
    description: "Intelectual que es dado a la gula, a los placeres, a la crítica social y a la vida moralmente desordenada"
  Lina:
    codename: lina
    name: Lina Marco
    display_name: Lina
    avatar: 'assets/images/miembros/lina.jpg'
    email: lina@astrologia.social
    web: https://lina.tecno.social
    description: "Astrología para la claridad no para la perfección"
    bio: "Nacida en Colombia, con sol y luna en Géminis y ascendente en Escorpio, tiene formación en comunicación, publicidad y marketing. Su relación con la astrología comenzó como un camino de autoconocimiento y sanación. En 2020, estudió en la escuela de astrología "La Maletra" (Bogotá, Colombia), donde, a través de la escritura íntima, profundizó en el misterio astrológico. Desde entonces, no ha dejado de intentar entender este enigma desde su propia curiosidad y capacidad de investigación. En el 2023, cursó la especialización en Astrología Mundana con Lu Gaitan en "Aprende Astrología" y actualmente está cursando la formación profesional en el Instituto Superior de Astrología (ISAA) de Argentina. En este tiempo, ha acompañado en la interpretación de mapas natales con un enfoque humanista y psicológico, utilizando también técnicas predictivas tradicionales con una mirada crítica y no determinista. Es cofundadora del proyecto Astrología Social, que apunta a la creación de una plataforma de diálogo y experimentación para albergar proyectos vinculados a diversos estudios del cosmos en relación con la experiencia humana, incluyendo la astrología occidental, pero no limitada a ella."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 3
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
