# Site
name: "Lina @ Astrologia.Social"
title: "Lina @ Astrologia.Social"
description: "La astrología es un lenguaje, si entiendes este lenguaje, el cielo te hablará. -Dane Rudhyar-"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.svg'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: lina@astrologia.social

# Authors
authors:
  Franco:
    name: Franco
    display_name: Fran
    avatar: 'assets/images/avatar-sal.png'
    email: info@tecno.social
    description: "Intelectual que es dado a la gula, a los placeres, a la crítica social y a la vida moralmente desordenada"
  Lina:
    name: Lina Marco
    display_name: Lina
    avatar: 'assets/images/avatar3.png'
    email: lina@astrologia.social
    web: lina.astrologia.social
    Instagram: https://www.instagram.com/linamarco1006/
    description: "Astrología para la claridad no para la perfección"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 3
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
